spring:
  application:
    name: backend
  #DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/steven
    username: root
    password: cxz20040622
server:
  port: 8080